#!/usr/bin/env node
/**
 * Generate android/local.properties from ANDROID_HOME so Gradle can find the SDK.
 * Run once after clone, or when Android build says "SDK location not found".
 *
 * Usage: node scripts/android-setup.js
 * Requires: ANDROID_HOME or ANDROID_SDK_ROOT set (e.g. $HOME/Library/Android/sdk on Mac)
 */

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const androidDir = path.join(root, 'android');
const localPropsPath = path.join(androidDir, 'local.properties');

const sdkRoot = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
const defaultMac = path.join(process.env.HOME || '', 'Library', 'Android', 'sdk');

function main() {
  const sdkPath = sdkRoot || (process.platform === 'darwin' && fs.existsSync(defaultMac) ? defaultMac : null);

  if (!sdkPath || !fs.existsSync(sdkPath)) {
    console.error('');
    console.error('Android SDK tidak ditemukan. Set ANDROID_HOME:');
    console.error('');
    console.error('  Mac (Android Studio):');
    console.error('    export ANDROID_HOME=$HOME/Library/Android/sdk');
    console.error('    export PATH=$ANDROID_HOME/platform-tools:$PATH');
    console.error('');
    console.error('  Simpan di ~/.zshrc lalu: source ~/.zshrc');
    console.error('');
    console.error('  Setelah pasang Android Studio / SDK, jalankan lagi:');
    console.error('    npm run android:setup');
    console.error('');
    process.exit(1);
  }

  if (!fs.existsSync(androidDir)) {
    console.error('Folder android/ belum ada. Jalankan dulu: npx expo prebuild --platform android');
    process.exit(1);
  }

  const content = `# Auto-generated by scripts/android-setup.js - do not commit if machine-specific
sdk.dir=${sdkPath.replace(/\\/g, '/')}
`;
  fs.writeFileSync(localPropsPath, content, 'utf8');
  console.log('OK: android/local.properties dibuat (sdk.dir=' + sdkPath + ')');
}

main();
